---
title: An introduction to MDI
author: Stephen Coleman
date: '2019-02-19'
slug: an-introduction-to-mdi
categories: []
tags:
  -MDI
  -Paul Kirk
bibliography: mdi.bib
---

# Multiple Dataset Integration

If we have observed paired datasets $X_1=(x_{1,1},\ldots, x_{n,1})$, 
$X_2=(x_{1,2},\ldots, x_{n,2})$, where observations in the $i$th row of each 
dataset represent information about the same individual. We would like to 
cluster using information common to both datasets. One could concatenate the
datasets, adding additional covariates for each individual. However, if the two
datasets have different clustering structures this would reduce the signal of 
both clusterings and probably have one dominate. If the two datasets have the 
same structure but different signal-to-noise ratios this would reduce the signal
in the final clustering. In both these cases independent models on each dataset 
would be preferable. @kirk2012bayesian suggest a method to carry out clustering 
on both datasets where common information is used but two individual clusterings 
are outputted. This method is driven by the allocation prior:

$$p(c_{i,1}, c_{i,2} | \phi ) \propto \pi_{i,1} \pi_{i,2} ( 1 + \phi \mathbb{I} ( c_{i,1} = c_{i,2}))$$

Here $\phi \in \mathbb{R}_{+}$ controls the strength of association between 
datasets. The above equation states that the probability of allocating 
individual $i$ to component $c_{i,1}$ in dataset 1 and to component $c_{i,2}$ in
dataset 2 is proportional to the proportion of these components within each 
dataset and up-weighted by $\phi$ if the individual has the same labelling in 
each dataset. Thus as $\phi$ grows the correlation between the clusterings grow 
and we are more likely to see the same clustering emerge from each dataset. 
Conversely if $\phi = 0$ we have independent mixture models. Note that
@kirk2012bayesian include the generalised case for $L$ datasets for any $L \in 
\mathbb{N}$.

MDI has been applied to precision medicine, specifically glioblastoma sub-typing
[@savage2013identifying], in the past showing its potential as a tool.

## References
